### ISSUE TITLE
Small errors in Bank example of locks.pdf

### ISSUE THREAD

**Issue by timotree3** [julesjacobs/diris#2]
Hi, [Higher-Order Leak and Deadlock Free Locks](https://julesjacobs.com/pdf/locks.pdf) is an awesome paper! I believe I noticed a couple of small errors in Example 2.3.4

![image](https://user-images.githubusercontent.com/6473438/224512881-6123a3cd-9e62-4ea3-b03d-da4a1c28fb01.png)

- Shouldn't the type of transaction include `int` argument for the amount?
- Shouldn't the second acquire(l1) be acquire(l2) instead?

**Comment by julesjacobs** [comment]
Hi Timo,

You are absolutely right; thanks for spotting the errors.
Unfortunately, I cannot change the published version, but I have put a fixed pdf online here: https://julesjacobs.com/pdf/locks.pdf

Best,
Jules
